// Code generated by mockery v2.1.0. DO NOT EDIT.

package mocks

import (
	entity "wagers/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// PurchaseRepository is an autogenerated mock type for the PurchaseRepository type
type PurchaseRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: pc
func (_m *PurchaseRepository) Create(pc *entity.Purchase) (*entity.Purchase, error) {
	ret := _m.Called(pc)

	var r0 *entity.Purchase
	if rf, ok := ret.Get(0).(func(*entity.Purchase) *entity.Purchase); ok {
		r0 = rf(pc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Purchase)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entity.Purchase) error); ok {
		r1 = rf(pc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryById provides a mock function with given fields: purchaseId
func (_m *PurchaseRepository) QueryById(purchaseId int) (*entity.Purchase, error) {
	ret := _m.Called(purchaseId)

	var r0 *entity.Purchase
	if rf, ok := ret.Get(0).(func(int) *entity.Purchase); ok {
		r0 = rf(purchaseId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Purchase)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(purchaseId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
